export type Service = {
  slug: string
  title: string
  headline: string
  description: string
  longDescription: string
  features: string[]
  faqs: { question: string; answer: string }[]
  category: string
  icon: string
}

export const services: Service[] = [
  {
    slug: 'accident-recovery',
    title: 'Accident Recovery',
    headline: '24/7 Professional Accident Recovery',
    description: 'Fast, safe vehicle recovery from road traffic accidents across Scotland. We manage the scene, protect your vehicle and coordinate with all parties.',
    longDescription: `When you're involved in a road traffic accident, the last thing you need is to worry about your vehicle. Glasgow Breakdown Recovery provides rapid, professional accident recovery services across Scotland 24 hours a day, 7 days a week, 365 days a year.\n\nOur experienced team arrives quickly, assesses the scene for safety, and uses specialist equipment to carefully recover your vehicle, whether it's a minor bump or a serious collision. We work closely with the police, insurance companies and repair garages to make the entire process as stress-free as possible.\n\nFrom Glasgow city centre to remote motorway stretches, we've seen and handled it all. No job is too complex.`,
    features: [
      'Scene safety assessment on arrival',
      'Specialist loading equipment for all vehicle types',
      'Coordination with police and emergency services',
      'Direct liaison with your insurance provider',
      'Delivery to your chosen garage or storage',
      'Evidence photography for insurance claims',
      'Nationwide recovery available',
      'Fully insured and certified operators',
    ],
    faqs: [
      {
        question: 'How quickly can you reach an accident scene in Scotland?',
        answer: 'We aim to reach most locations across Central Scotland within 45–60 minutes of your call. Response times may vary depending on location and traffic conditions, but we dispatch immediately around the clock.',
      },
      {
        question: 'Do you work with all insurance companies?',
        answer: 'Yes, Glasgow Breakdown Recovery works with all major UK insurance providers. We can handle the communication directly if you prefer, reducing the stress on you after an accident.',
      },
      {
        question: 'What happens to my car after recovery?',
        answer: 'Your vehicle will be delivered to your chosen garage, or we can recommend a trusted local repair centre. We also offer secure storage if your garage cannot accept the vehicle immediately.',
      },
      {
        question: 'Can you recover vehicles from motorways?',
        answer: 'Absolutely. We are fully trained and equipped for motorway recovery operations. We follow all statutory motorway safety protocols to ensure you and our team stay safe during the recovery.',
      },
    ],
    category: 'Emergency Services',
    icon: '🚨',
  },
  {
    slug: 'breakdown-recovery',
    title: 'Breakdown Recovery',
    headline: 'Roadside Breakdown Assistance',
    description: 'Broken down on the side of the road? We will reach you fast and get your vehicle recovered or repaired on the spot.',
    longDescription: `Vehicle breakdowns never happen at a convenient time. Whether your engine has given up on a quiet backstreet or you have run out of fuel on the motorway, Glasgow Breakdown Recovery is ready to help immediately.\n\nOur recovery vehicles are fully equipped to handle a wide range of breakdown scenarios. In many cases, our technicians can carry out roadside repairs to get you moving again without the need for a tow. When that is not possible, we will safely transport your vehicle to your preferred garage.`,
    features: [
      'Rapid roadside response',
      'On-the-spot minor repairs where possible',
      'Battery jump-starts and tyre changes',
      'Fuel delivery for run-out situations',
      'Flatbed and wheel-lift towing',
      'Coverage across all of Scotland',
      'Secure vehicle transportation',
      'Friendly, knowledgeable technicians',
    ],
    faqs: [
      {
        question: 'Can you repair my car at the roadside?',
        answer: 'In many cases yes, we can handle battery issues, flat tyres, minor mechanical problems and fuel emergencies at the roadside. If the vehicle cannot be repaired on the spot, we will tow it to a garage.',
      },
      {
        question: 'Is breakdown recovery covered by my insurance?',
        answer: "It depends on your policy. Some comprehensive insurance policies include breakdown cover as standard. Check your documents or call your insurer. If you don't have cover, we offer competitive pay-per-use pricing.",
      },
      {
        question: 'What should I do while I wait for recovery?',
        answer: 'Stay in your vehicle with your seatbelt on if it is safe to do so. Turn on your hazard lights. If you must exit the vehicle, move well away from traffic. Never stand on the carriageway.',
      },
    ],
    category: 'Breakdown',
    icon: '🔧',
  },
  {
    slug: 'motorway-recovery',
    title: 'Motorway Recovery',
    headline: 'Fast Motorway Emergency Recovery',
    description: 'Specialist motorway recovery for the M8, M74, M77, M73, M80 and all Scottish motorway network. Rapid response, full compliance.',
    longDescription: `Motorway breakdowns and accidents present unique challenges that require specialist training and equipment. Glasgow Breakdown Recovery holds all necessary certifications for motorway recovery operations across Scotland's busy motorway network.\n\nWe operate on all of Scotland's major motorways including the M8, M74, M77, M73, M80, M876 and the A-roads leading to them. Our team is trained in live-lane working protocols and uses the highest-specification vehicles to safely recover cars, vans, motorcycles and light commercial vehicles.`,
    features: [
      'Certified motorway recovery operators',
      'Full compliance with Highways England protocols',
      'Emergency attendance on all Scottish motorways',
      'Traffic management and scene safety',
      'Long reach equipment for difficult recoveries',
      'Out-of-hours and bank holiday availability',
      'Works alongside Police Scotland motorway units',
      'Competitive fixed pricing, no motorway surcharge',
    ],
    faqs: [
      {
        question: 'Is there an extra charge for motorway recovery?',
        answer: 'No. Unlike some providers, Glasgow Breakdown Recovery does not apply a motorway surcharge. You receive the same transparent pricing regardless of where you have broken down.',
      },
      {
        question: 'How do I safely call for help on a motorway?',
        answer: "If possible, reach an emergency refuge area (ERA) or a hard shoulder. Use a motorway SOS phone or call us on your mobile. Stay behind the barrier and away from the live carriageway while you wait.",
      },
      {
        question: 'Which motorways do you cover?',
        answer: 'We cover the entire Scottish motorway network including M8, M74, M77, M73, M80, M9, M876, and all connecting A-roads. We also extend to cross-border motorways when required.',
      },
    ],
    category: 'Motorway',
    icon: '🛣️',
  },
  {
    slug: 'flatbed-towing',
    title: 'Flatbed Towing',
    headline: 'Safe Flatbed Vehicle Transportation',
    description: 'Full flatbed transport for cars, vans, prestige vehicles and modified cars that cannot be conventional towed.',
    longDescription: `Not every vehicle can be towed using a traditional A-frame or wheel-lift. Low-profile sports cars, all-wheel-drive vehicles, prestige cars and severely damaged vehicles all require flatbed transportation to avoid further damage.\n\nGlasgow Breakdown Recovery's modern flatbed fleet ensures your vehicle is loaded using a hydraulic tilt-bed system and secured with professional strapping throughout the journey. Your vehicle arrives at its destination in exactly the same condition it left.`,
    features: [
      'Modern hydraulic tilt-bed flatbeds',
      'Safe for all-wheel-drive and 4x4 vehicles',
      'Ideal for prestige and sports cars',
      'Severely damaged vehicle specialists',
      'Fully strapped and secured loads',
      'Short and long distance transportation',
      'Collection from any location',
      'Available 24/7',
    ],
    faqs: [
      {
        question: 'Does flatbed towing cost more than regular towing?',
        answer: 'Flatbed transportation is priced competitively with our standard recovery. The extra care taken with your vehicle is included in our standard rate. Contact us for a quote.',
      },
      {
        question: 'Can you flatbed my prestige or sports car?',
        answer: 'Absolutely. We regularly transport prestige vehicles including BMW, Mercedes, Audi, Porsche and others on our flatbeds. We understand how valuable your vehicle is and treat it accordingly.',
      },
    ],
    category: 'Towing',
    icon: '🚛',
  },
  {
    slug: 'accident-claims',
    title: 'Accident Claims Assistance',
    headline: 'Expert Accident Claims Support',
    description: 'We make it easy to navigate insurance claims after an accident. Our team guides you through every step from documentation to settlement.',
    longDescription: `Filing an insurance claim after a road traffic accident can feel overwhelming, especially when you are already dealing with the stress of the accident itself. Glasgow Breakdown Recovery provides expert accident claims assistance to help you get the compensation and repairs you deserve.\n\nFrom gathering photographic evidence at the scene to liaising with insurers and solicitors, our team handles the paperwork so you can focus on recovering.`,
    features: [
      'Scene documentation and photography',
      'Insurance liaison on your behalf',
      'No-fault accident support',
      'Claim form assistance',
      'Uninsured driver claims guidance',
      'Whiplash and injury claim referrals',
      'Vehicle damage assessment',
      'Courtesy car arrangement support',
    ],
    faqs: [
      {
        question: 'What is a non-fault accident claim?',
        answer: "If you are involved in an accident that was not your fault, you may be entitled to have your vehicle repaired or replaced at no cost to you, and your no-claims bonus protected. Our team can help you understand your rights.",
      },
      {
        question: 'How long do I have to make an accident claim in Scotland?',
        answer: 'For personal injury claims in Scotland, you generally have 3 years from the date of the accident. For vehicle damage claims, it is important to notify your insurer promptly, ideally within 24 hours.',
      },
    ],
    category: 'Claims',
    icon: '📋',
  },
  {
    slug: 'long-distance-recovery',
    title: 'Long Distance Recovery',
    headline: 'UK-Wide Long Distance Recovery',
    description: 'Need your vehicle recovered from anywhere in the UK? We offer long-distance recovery to get your vehicle home, wherever you break down.',
    longDescription: `Breaking down far from home is stressful enough without having to worry about finding a reliable local recovery service you have never heard of. Glasgow Breakdown Recovery offers long-distance recovery across the entire UK, so you can trust a team you know even when you are miles from Scotland.\n\nWhether you have broken down in England, Wales or anywhere else in the UK, we will come to you or arrange trusted partner recovery, then transport your vehicle back to Scotland or your chosen destination.`,
    features: [
      'UK-wide recovery capability',
      'Partner network for remote locations',
      'Overnight stay arrangements if required',
      'Direct driver communication throughout',
      'Transparent long-distance pricing',
      'Vehicle tracking during transport',
      'Secure overnight storage available',
      'Passenger transport options',
    ],
    faqs: [
      {
        question: 'How do you price long-distance recovery?',
        answer: 'Long-distance recovery is priced per mile on a transparent scale. Call us for a quote, we will provide a fixed price before we begin so there are no surprises.',
      },
      {
        question: 'Can you recover my vehicle from England to Scotland?',
        answer: 'Yes, this is one of our most common long-distance requests. We regularly recover vehicles from across England and Wales back to Scotland for our customers.',
      },
    ],
    category: 'Long Distance',
    icon: '📍',
  },
  {
    slug: 'motorcycle-recovery',
    title: 'Motorcycle Recovery',
    headline: 'Specialist Motorcycle Recovery',
    description: 'Dedicated motorcycle recovery with specialist equipment to safely transport your bike without damage.',
    longDescription: `Motorcycles require specialist recovery equipment and handling techniques to avoid damage during loading and transportation. Glasgow Breakdown Recovery operates dedicated motorcycle recovery vehicles with purpose-built loading ramps, wheel chocks and securing straps designed specifically for motorcycles.\n\nWhether you have had an accident or suffered a mechanical failure, we treat your motorcycle with the same care you do.`,
    features: [
      'Purpose-built motorcycle transport vehicles',
      'Specialist wheel chock securing systems',
      'Accident recovery for all bike types',
      'Sports bike specialists',
      'Scooter and moped recovery',
      'Off-road and adventure bike capability',
      'Secure loading and unloading',
      '24/7 availability',
    ],
    faqs: [
      {
        question: 'Can you recover a motorcycle that has been in an accident?',
        answer: 'Yes. We have specialist equipment for loading damaged motorcycles without causing further damage. Our team handles bikes with care from scene collection to garage delivery.',
      },
      {
        question: 'Do you carry spare parts for motorcycles?',
        answer: 'Our primary service is recovery and transportation. For minor issues such as flat tyres, we may be able to assist at the roadside. For mechanical repairs, we will transport you to a specialist motorcycle garage.',
      },
    ],
    category: 'Specialist',
    icon: '🏍️',
  },
  {
    slug: 'commercial-vehicle-recovery',
    title: 'Commercial Vehicle Recovery',
    headline: 'Van & Light Commercial Recovery',
    description: 'Fast recovery for vans, light trucks, minibuses and commercial vehicles. We understand the cost of downtime and move fast.',
    longDescription: `When a commercial vehicle breaks down, every minute of downtime costs money. Glasgow Breakdown Recovery understands the urgency of commercial breakdowns and prioritises fast dispatch for all commercial vehicle recovery calls.\n\nWe recover and transport all types of light commercial vehicles up to 7.5 tonnes, including transit vans, Sprinters, Transporters, flatbed trucks and minibuses. Our heavy-duty recovery fleet handles anything up to the legal limit for our licences.`,
    features: [
      'Light commercial vehicles up to 7.5t',
      'Transit vans, Sprinters and Transporters',
      'Flatbed trucks and tippers',
      'Minibus recovery',
      'Priority dispatch for commercial calls',
      'Account services available for fleets',
      'Invoice billing for business customers',
      'Throughout Scotland and beyond',
    ],
    faqs: [
      {
        question: 'Do you offer fleet recovery accounts?',
        answer: 'Yes, we offer fleet accounts for businesses with multiple vehicles. Account customers receive priority dispatch, monthly invoicing and dedicated account management. Contact us to set up an account.',
      },
      {
        question: 'What is the maximum vehicle weight you recover?',
        answer: 'Our primary fleet handles vehicles up to 7.5 tonnes. For heavier vehicles, we have partner operators with heavy recovery capability. Contact us and we will arrange the right recovery solution.',
      },
    ],
    category: 'Commercial',
    icon: '🚚',
  },
  {
    slug: 'emergency-recovery',
    title: 'Emergency Recovery',
    headline: '24/7 Priority Emergency Recovery',
    description: '24/7 emergency recovery with an average response under one hour. Accidents, live lane incidents, unsafe roadside situations and total breakdowns, prioritised by urgency and risk. Covering Glasgow, Edinburgh and the whole Scottish central belt.',
    longDescription: `Some call-outs simply cannot wait. A car stranded in a live lane, a vehicle blocking a junction, or a driver stuck somewhere unsafe all get moved to the front of the queue the moment you call. Glasgow Breakdown Recovery runs a genuine priority dispatch system, so the most dangerous situations are never left waiting behind routine jobs.\n\nOur controllers assess risk on the phone, not just distance, before deciding which truck moves first. That means a breakdown on a quiet side street might wait slightly longer than a car straddling a motorway lane, even if the second call came in after yours. It is a fairer system, and it is the one that keeps people safe.`,
    features: [
      'Risk-based priority dispatch, not first-come-first-served',
      'Average response under one hour across Central Scotland',
      'Live lane and hard shoulder incidents prioritised',
      'Direct line, no call-centre queue',
      'Coordination with police and Traffic Scotland where needed',
      'Covers accidents, breakdowns and unsafe roadside situations',
      'Glasgow, Edinburgh and the Scottish central belt',
      'Available 24 hours a day, 365 days a year',
    ],
    faqs: [
      {
        question: 'What counts as an emergency recovery call?',
        answer: 'Anything involving immediate danger: a vehicle in a live lane, blocking a road, or a driver left somewhere unsafe. Tell us the situation on the phone and we will assess and dispatch accordingly.',
      },
      {
        question: 'Will I be prioritised over other jobs on the road?',
        answer: 'If your situation carries more risk than the jobs already in our queue, yes. Our controllers weigh danger and urgency, not just who called first.',
      },
      {
        question: 'Is emergency recovery more expensive than standard recovery?',
        answer: 'No, there is no emergency surcharge. You get the same transparent pricing, just with faster, risk-based dispatch.',
      },
    ],
    category: 'Emergency Services',
    icon: '🆘',
  },
  {
    slug: '24-hour-recovery',
    title: '24 Hour Recovery',
    headline: 'Recovery, Open 24 Hours',
    description: 'Open 24 hours, seven days, including bank holidays and Christmas Day. Same service, same operators, same pricing whatever time you call. Based in Central Scotland with a 30-mile rapid-response core zone. Call and speak to someone straight away.',
    longDescription: `A lot of recovery firms advertise "24 hour" service and then route late calls through an answering service or a subcontractor you have never dealt with. Glasgow Breakdown Recovery does not do that. Whoever answers at 3am is the same team, running the same trucks, at the same prices as midday.\n\nWe are based in Central Scotland with a roughly 30-mile core zone where response is fastest, extending further for anyone travelling through or breaking down further out. Whatever the hour, whatever the day of the year, you speak to a real person straight away, not a message asking you to try again in the morning.`,
    features: [
      'Genuinely staffed 24 hours a day, every day',
      'Open Christmas Day, New Year and all bank holidays',
      'Same team and pricing regardless of time of call',
      'No answering service or overnight subcontracting',
      '30-mile rapid-response core zone from our Central Scotland base',
      'Extended coverage available further out',
      'Speak to a person immediately, no automated queue',
      'Cars, vans, motorcycles and commercial vehicles covered',
    ],
    faqs: [
      {
        question: 'Are you really open all night, or does it go to an answering machine?',
        answer: "A real person answers, day or night. There's no answering machine and no overnight handoff to a different company.",
      },
      {
        question: 'Do you charge more for a call at 3am than 3pm?',
        answer: 'No, pricing is identical whatever time you call, including bank holidays and Christmas Day.',
      },
      {
        question: 'How far from Central Scotland do you cover overnight?',
        answer: 'Our fastest response is within roughly 30 miles of base, but we take calls from further afield too. Just tell us your location and we will confirm a price and ETA.',
      },
    ],
    category: 'Emergency Services',
    icon: '🕐',
  },
  {
    slug: 'electric-vehicle-recovery',
    title: 'Electric Vehicle Recovery',
    headline: 'Flatbed-Only EV Recovery',
    description: 'EV recovery on flatbed only, as manufacturers require. No towing, no drivetrain damage, no risk to the battery pack. Teslas, hybrids and all electric models transported safely to your home, dealer or charge point. Glasgow, Edinburgh and Scotland-wide.',
    longDescription: `Electric and hybrid vehicles cannot be towed with a conventional A-frame or wheel-lift. Manufacturers are explicit about this, because towing with the wheels turning can damage the motor and, in some cases, put the battery pack at risk. Every EV recovery we carry out goes on a flatbed, with all four wheels off the road, exactly as the manufacturer requires.\n\nWe regularly recover Teslas, hybrids and fully electric models from every major manufacturer, delivering to your home, a dealership, a specialist EV garage or the nearest charge point if the issue is simply a flat battery. Our drivers understand the extra care EVs need when loading and securing, including isolation points and low ground clearance on some models.`,
    features: [
      'Flatbed only, as required by EV and hybrid manufacturers',
      'No towing, zero risk to motor or battery pack',
      'Teslas, hybrids and all fully electric models',
      'Low ground clearance loading experience',
      'Delivery to home, dealer, specialist garage or charge point',
      'Fully insured in transit',
      'Glasgow, Edinburgh and Scotland-wide coverage',
      'Available 24 hours a day',
    ],
    faqs: [
      {
        question: 'Can my electric car be towed instead of flatbedded?',
        answer: 'No, nearly all EV and hybrid manufacturers require flatbed-only recovery, since towing with the wheels turning can damage the motor or drivetrain. We always flatbed electric vehicles.',
      },
      {
        question: 'What if my EV has simply run out of charge?',
        answer: 'We can transport it to the nearest suitable charge point, your home charger, or a dealership, whichever makes most sense for you.',
      },
      {
        question: 'Do you have experience with low-clearance EVs?',
        answer: 'Yes, several EV models sit very low to the ground. Our drivers know which models need extra care when loading and use the correct ramp angle and jacking points.',
      },
    ],
    category: 'Specialist',
    icon: '🔋',
  },
  {
    slug: 'prestige-vehicle-recovery',
    title: 'Prestige Vehicle Recovery',
    headline: 'Prestige & Sports Car Recovery',
    description: 'Prestige and sports car recovery on hydraulic tilt-bed flatbeds with low approach angles. Ideal for lowered, modified and high-value vehicles that cannot go on a conventional tow. Fully insured in transit. Covering Glasgow, Edinburgh and Scotland.',
    longDescription: `Lowered suspension, wide arches and minimal ground clearance make prestige and sports cars some of the most demanding vehicles to recover safely. A standard tow truck's approach angle simply is not shallow enough, and the wrong equipment can mean scraped splitters, damaged sills or worse.\n\nOur hydraulic tilt-bed flatbeds are built for exactly this problem, with a low, gradual loading angle and soft strapping that protects paintwork and bodywork throughout the journey. We regularly recover BMW, Mercedes, Audi, Porsche and other prestige marques across Glasgow, Edinburgh and Central Scotland, and every job is fully insured in transit.`,
    features: [
      'Hydraulic tilt-bed flatbeds with low approach angles',
      'Suitable for lowered and modified vehicles',
      'Soft strapping to protect paintwork and bodywork',
      'Experience with BMW, Mercedes, Audi, Porsche and more',
      'Fully insured in transit',
      'Careful, unhurried loading and unloading',
      'Glasgow, Edinburgh and Central Scotland coverage',
      'Available 24/7',
    ],
    faqs: [
      {
        question: 'Will a standard tow truck damage my lowered car?',
        answer: 'It can: the approach angle on a standard tow truck is often too steep for lowered or modified vehicles. We use hydraulic tilt-bed flatbeds specifically to avoid that risk.',
      },
      {
        question: 'Are you insured to carry high-value vehicles?',
        answer: 'Yes, every recovery is fully insured in transit, whatever the value of the vehicle.',
      },
      {
        question: 'Do you have experience with specific prestige brands?',
        answer: 'We regularly recover BMW, Mercedes-Benz, Audi, Porsche and other prestige and performance marques, and take the same careful approach with every one.',
      },
    ],
    category: 'Specialist',
    icon: '🏎️',
  },
  {
    slug: '4x4-awd-recovery',
    title: '4x4 and AWD Recovery',
    headline: '4x4 & All-Wheel-Drive Recovery',
    description: 'All-wheel-drive and 4x4 recovery done properly on a flatbed, with all four wheels off the road to protect the transmission. Land Rovers, pickups, SUVs and permanent AWD cars. Serving Glasgow, Edinburgh and across Central Scotland, 24 hours a day.',
    longDescription: `Permanent all-wheel-drive and four-wheel-drive vehicles can be seriously damaged by conventional towing, which drags one axle along the road while the transmission is still engaged. That mismatch in wheel speed can wreck a transfer case or differential in minutes, turning a simple breakdown into an expensive repair.\n\nWe recover every 4x4 and AWD vehicle on a flatbed, with all four wheels lifted clear of the road, protecting the drivetrain completely. This covers everything from Land Rovers and pickups to SUVs and performance AWD cars, across Glasgow, Edinburgh and the rest of Central Scotland.`,
    features: [
      'Flatbed recovery with all four wheels off the road',
      'Protects transfer case and differential from tow damage',
      'Land Rovers, pickups and SUVs',
      'Permanent AWD performance cars',
      'Off-road and rural recovery experience',
      'Correct strapping for high ground clearance vehicles',
      'Glasgow, Edinburgh and Central Scotland',
      '24/7 availability',
    ],
    faqs: [
      {
        question: 'Why can\'t my 4x4 be towed normally?',
        answer: 'Permanent four-wheel-drive and AWD systems can be damaged when one set of wheels is dragged while the drivetrain is still connected. Flatbed transport avoids this entirely.',
      },
      {
        question: 'Do you recover 4x4s from off-road or rural locations?',
        answer: 'Yes, we regularly recover vehicles from farm tracks, fields and rural roads. If winching is needed to reach the vehicle first, we carry that equipment too.',
      },
    ],
    category: 'Specialist',
    icon: '🚙',
  },
  {
    slug: 'car-recovery',
    title: 'Car Recovery',
    headline: 'Car Recovery Across Central Scotland',
    description: "Car recovery across Central Scotland, 24/7. Breakdowns, non-runners, accident damage and vehicles that simply won't move, loaded securely and taken to your home, garage or destination of choice. Local recovery from £60 plus £1.50 per mile.",
    longDescription: `Whatever has stopped your car moving, a dead battery, a mechanical failure, accident damage or simply a non-runner sitting on the drive, Glasgow Breakdown Recovery will collect it and take it wherever you need it to go. This is our most common call-out, and it is priced simply: local recovery starts from £60 plus £1.50 per mile, confirmed on the phone before we dispatch.\n\nWe cover the whole of Central Scotland, from city centre streets to rural roads, and treat every car the same way regardless of age or value, secured properly and driven carefully to your home, garage or wherever you choose.`,
    features: [
      'Breakdowns, non-runners and accident-damaged cars',
      'Local recovery from £60 plus £1.50 per mile',
      'Clear price confirmed before we set off',
      'Delivery to your home, garage or destination of choice',
      'All makes and ages of car',
      'Central Scotland-wide coverage',
      'Careful loading and secure transport',
      'Available 24 hours a day, every day',
    ],
    faqs: [
      {
        question: 'How much does car recovery cost?',
        answer: 'Local recovery starts from £60 plus £1.50 per mile. We confirm the exact total on the phone before dispatching, so there are no surprises.',
      },
      {
        question: 'Can you recover a car that won\'t start at all?',
        answer: "Yes, that's one of our most common jobs, whether it's a flat battery, mechanical fault or non-runner. We'll load it and take it wherever you need.",
      },
    ],
    category: 'Breakdown',
    icon: '🚗',
  },
  {
    slug: 'van-recovery',
    title: 'Van Recovery',
    headline: 'Van Recovery, Glasgow & Edinburgh',
    description: 'Van recovery across Glasgow, Edinburgh and Central Scotland. Transits, Sprinters, Transporters and Lutons recovered with tools and load kept secure. Priority dispatch on fleet accounts. Clear price quoted on the phone before we set off.',
    longDescription: `A van breakdown is rarely just about the vehicle: there is usually a load, tools or a schedule riding on it too. Glasgow Breakdown Recovery recovers Transits, Sprinters, Transporters, Lutons and similar light commercials across Glasgow, Edinburgh and Central Scotland, taking care to keep the load and any tools on board secure throughout.\n\nTrade and business customers can set up a fleet account for priority dispatch and monthly invoicing, but one-off call-outs are just as welcome, with a clear price agreed on the phone before we come out.`,
    features: [
      'Transits, Sprinters, Transporters and Lutons',
      'Load and tools kept secure during recovery',
      'Priority dispatch available on fleet accounts',
      'One-off call-outs welcome, no account required',
      'Clear price quoted before dispatch',
      'Glasgow, Edinburgh and Central Scotland coverage',
      'Suitable for tradespeople and business fleets',
      'Available 24 hours a day, 365 days a year',
    ],
    faqs: [
      {
        question: 'Will my tools and load be safe during recovery?',
        answer: 'Yes, we secure any load and tools on board before transport and take care not to disturb racking or fitted-out interiors.',
      },
      {
        question: 'Can I set up an account for regular van recovery?',
        answer: 'Yes, we offer fleet accounts with priority dispatch and monthly invoicing for businesses that need recovery regularly.',
      },
    ],
    category: 'Commercial',
    icon: '🚐',
  },
  {
    slug: 'jump-start-service',
    title: 'Jump Start Service',
    headline: 'Flat Battery? Jump Start Service',
    description: 'Flat battery? We attend with professional jump packs and get you started at the roadside, no tow needed in most cases. Part of our standard breakdown response across Glasgow, Edinburgh and Central Scotland. Available 24 hours a day, 365 days a year.',
    longDescription: `A flat battery is one of the most common breakdown calls we get, and in most cases it is also the quickest to resolve. Our recovery vehicles carry professional-grade jump packs capable of starting anything from a small hatchback to a larger diesel engine, so in the majority of cases you are back on the road within minutes, no tow required.\n\nIf the battery turns out to be beyond a simple jump start, perhaps it is old, damaged or the alternator is not charging, we will explain what we have found and arrange recovery to a garage from there.`,
    features: [
      'Professional-grade jump packs on every vehicle',
      'Most jump starts resolved in minutes, no tow needed',
      'Covers petrol and diesel vehicles',
      'Honest advice if the battery needs replacing',
      'Full recovery arranged if a jump start isn\'t enough',
      'Included as standard in our breakdown response',
      'Glasgow, Edinburgh and Central Scotland',
      'Available 24 hours a day, 365 days a year',
    ],
    faqs: [
      {
        question: 'Will a jump start definitely get my car going?',
        answer: 'In most cases, yes. If the issue is genuinely just a flat battery, our jump packs will get you started. If the battery or alternator is faulty, we will let you know and arrange recovery.',
      },
      {
        question: 'Is a jump start included in a normal call-out?',
        answer: 'Yes, it is part of our standard breakdown response, and there is no separate charge for attempting a jump start.',
      },
    ],
    category: 'Breakdown',
    icon: '⚡',
  },
  {
    slug: 'flat-tyre-assistance',
    title: 'Flat Tyre Assistance',
    headline: 'Flat Tyre & Puncture Assistance',
    description: 'Puncture or blowout handled at the roadside. We fit your spare where there is one, or recover the vehicle if the wheel is damaged or no spare is carried. Included in our breakdown callout. Glasgow, Edinburgh and Central Scotland, 24 hours.',
    longDescription: `A puncture or blowout is usually straightforward to sort at the roadside, provided you are carrying a spare wheel or a working repair kit. We will fit your spare safely, well away from live traffic where possible, and get you moving again.\n\nMany newer cars come with a space-saver spare, a repair kit only, or no spare at all. If that is the case, or if the wheel itself is damaged, we will recover the vehicle to a tyre garage or your preferred destination instead. Either way, it is covered under our standard breakdown call-out.`,
    features: [
      'Roadside spare wheel fitting',
      'Blowout and puncture response',
      'Recovery arranged if no usable spare is carried',
      'Recovery arranged if the wheel or rim is damaged',
      'Safe working practices away from live traffic',
      'Included in our standard breakdown call-out',
      'Glasgow, Edinburgh and Central Scotland',
      'Available 24 hours a day',
    ],
    faqs: [
      {
        question: 'What if I don\'t have a spare wheel?',
        answer: "Many newer cars only carry a repair kit or nothing at all. If that's the case, we will recover your car to the nearest tyre garage or your preferred destination.",
      },
      {
        question: 'Is there an extra charge for changing a tyre?',
        answer: 'No, roadside tyre changes are included as part of our standard breakdown call-out.',
      },
    ],
    category: 'Breakdown',
    icon: '🛞',
  },
  {
    slug: 'winching-service',
    title: 'Winching Service',
    headline: 'Winch Recovery: Stuck, Not Broken',
    description: 'Winch recovery for vehicles off the carriageway, in ditches, on verges or stuck on soft ground. Proper gear and correct recovery points used so nothing gets bent. £40 winch fee applied only where needed. Covering Central Scotland, 24/7.',
    longDescription: `Sometimes a vehicle isn't broken down at all, it's just stuck. A verge that gave way in the rain, a wheel dropped into a ditch, or a car bogged down on soft ground after leaving the road all need winching rather than a straightforward tow. Using the wrong technique or the wrong recovery point can bend a chassis rail or tear a bumper clean off.\n\nOur trucks carry proper winching equipment and our drivers know where the correct rated recovery points are on most vehicles, so your car comes back onto solid ground without new damage being added to the old problem. A £40 winch fee applies only when winching is actually required, on top of standard recovery.`,
    features: [
      'Proper winching equipment on every truck',
      'Correct, rated recovery points used, no bent bumpers',
      'Vehicles in ditches, verges and soft ground',
      'Off-road and field recovery experience',
      '£40 winch fee, applied only when winching is needed',
      'Combined with recovery to your chosen destination',
      'Central Scotland coverage',
      'Available 24/7',
    ],
    faqs: [
      {
        question: 'How much does winching cost?',
        answer: 'A £40 winch fee applies on top of standard recovery, but only when winching is actually required to free the vehicle.',
      },
      {
        question: 'Will winching damage my car?',
        answer: 'Not when done correctly. We use the manufacturer-rated recovery points on your vehicle, not the bumper or trim, to avoid causing further damage.',
      },
    ],
    category: 'Specialist',
    icon: '⛓️',
  },
  {
    slug: 'vehicle-transport',
    title: 'Vehicle Transport',
    headline: 'Single Vehicle Transport, UK-Wide',
    description: 'Single vehicle transport across Scotland and the UK on flatbed or trailer, fully insured in transit. Purchases, auction buys, project cars and non-runners collected and delivered. Fixed price quoted up front with no hidden mileage charges.',
    longDescription: `Not every job we do starts with a breakdown. We regularly move vehicles that simply need transporting from one place to another, a car bought at auction, a private purchase collected from a seller, a project car heading to storage, or a non-runner going for repair or restoration.\n\nEvery transport job is quoted as a fixed price before we collect, based on distance and vehicle type, so there are no hidden mileage charges once we're underway. Vehicles travel on flatbed or trailer as appropriate and are fully insured for the journey.`,
    features: [
      'Auction and private purchase collection',
      'Project cars and non-runners',
      'Flatbed or trailer transport as appropriate',
      'Fixed price quoted before collection',
      'No hidden mileage charges',
      'Fully insured in transit',
      'Scotland and UK-wide',
      'Flexible collection and delivery scheduling',
    ],
    faqs: [
      {
        question: 'Can you collect a car I\'ve bought at auction?',
        answer: 'Yes, this is a regular job for us. Give us the collection and delivery addresses and vehicle details, and we will quote a fixed price up front.',
      },
      {
        question: 'Does the vehicle need to be running?',
        answer: 'No, we regularly transport non-runners and project cars using flatbed or trailer transport as needed.',
      },
    ],
    category: 'Towing',
    icon: '🛻',
  },
  {
    slug: 'fleet-recovery',
    title: 'Fleet Recovery',
    headline: 'Fleet & Trade Recovery Accounts',
    description: 'Fleet and trade recovery accounts for garages, dealerships, hire firms and commercial operators. Priority dispatch, agreed rates and account invoicing so downtime is predictable. Covering Glasgow, Edinburgh and Central Scotland, 24 hours a day.',
    longDescription: `For garages, dealerships, hire companies and businesses running multiple vehicles, breakdowns are a cost of doing business, but unpredictable recovery bills and slow response times make that cost harder to manage. Our fleet accounts are built to fix that.\n\nAccount customers get priority dispatch ahead of general call-outs, pre-agreed rates so there are no surprises invoice to invoice, and monthly billing instead of paying on the day. It suits garages needing regular vehicle movements just as much as operators dealing with occasional breakdowns across a larger fleet.`,
    features: [
      'Priority dispatch ahead of general call-outs',
      'Pre-agreed rates, no per-job negotiation',
      'Monthly account invoicing',
      'Suited to garages, dealerships and hire firms',
      'Suited to commercial operators with multiple vehicles',
      'Single point of contact for all recovery needs',
      'Glasgow, Edinburgh and Central Scotland',
      'Available 24 hours a day',
    ],
    faqs: [
      {
        question: 'How do I set up a fleet account?',
        answer: 'Contact us with your business details and typical vehicle types, and we will agree rates and set up monthly invoicing before your first call-out.',
      },
      {
        question: 'Is there a minimum number of vehicles for an account?',
        answer: 'No fixed minimum: we set up accounts for single-vehicle garages right through to larger commercial fleets.',
      },
    ],
    category: 'Commercial',
    icon: '🏢',
  },
  {
    slug: 'no-fault-accident-support',
    title: 'No-Fault Accident Support',
    headline: 'No-Fault Accident Support',
    description: 'No-fault accident support that takes the admin off you. We document the scene, deal with the insurer and guide the claim through to settlement. Free consultation before you commit to anything. Serving Glasgow, Edinburgh and Central Scotland.',
    longDescription: `Being involved in an accident that wasn't your fault shouldn't mean you're left to chase paperwork and phone calls on top of everything else. Glasgow Breakdown Recovery's no-fault accident support handles the admin side directly, from documenting the scene at the point of recovery through to liaising with the at-fault driver's insurer.\n\nWe offer a free, no-obligation consultation first, so you understand exactly what support is available and what it involves before agreeing to anything. Our aim is to get your vehicle repaired or replaced and your claim settled with as little disruption to you as possible.`,
    features: [
      'Free, no-obligation initial consultation',
      'Scene documentation and photography at recovery',
      'Direct liaison with the at-fault driver\'s insurer',
      'Claim guided through to settlement',
      'No-claims bonus protection support',
      'Courtesy car arrangement guidance',
      'Glasgow, Edinburgh and Central Scotland',
      'Available 24 hours a day',
    ],
    faqs: [
      {
        question: 'Does the consultation commit me to anything?',
        answer: 'No, the initial consultation is free and no-obligation. You decide afterwards whether you want us to support your claim.',
      },
      {
        question: 'Will pursuing a no-fault claim affect my no-claims bonus?',
        answer: "If the accident genuinely wasn't your fault, your no-claims bonus should be protected. We help make sure this is handled correctly with the insurer involved.",
      },
    ],
    category: 'Claims',
    icon: '⚖️',
  },
  {
    slug: 'accident-recovery-glasgow',
    title: 'Accident Recovery in Glasgow',
    headline: '24/7 Accident Recovery in Glasgow',
    description: '24/7 accident recovery across Glasgow, from the city centre to the motorway network. We make the scene safe, recover your vehicle and support the insurance claim afterwards. Average response under an hour. Free claims consultation included.',
    longDescription: `Glasgow's mix of tight city centre streets, the elevated M8 viaduct and busy ring roads means accident recovery here needs local knowledge as much as it needs speed. Glasgow Breakdown Recovery is based in the city and covers every G postcode, from the Southside and West End through to the East End and beyond, typically arriving within 30–45 minutes.\n\nOn arrival, we make the scene safe first, then recover your vehicle using the right equipment for the damage involved. We coordinate directly with Police Scotland where they're in attendance, and once your vehicle is safely recovered, our free claims consultation is there to help with the insurance side of things.`,
    features: [
      'Covers all Glasgow G postcode districts',
      'Average response 30–45 minutes',
      'M8 viaduct and Kingston Bridge experience',
      'Scene safety assessment on arrival',
      'Coordination with Police Scotland when in attendance',
      'Free accident claims consultation included',
      'Delivery to your chosen garage or storage',
      'Available 24 hours a day, 365 days a year',
    ],
    faqs: [
      {
        question: 'How quickly can you reach an accident in central Glasgow?',
        answer: 'For central postcodes such as G1, G2 and G3, we typically arrive within 30–40 minutes. Outer Glasgow postcodes may take up to 60 minutes depending on traffic.',
      },
      {
        question: 'Do you recover vehicles from the M8 through Glasgow?',
        answer: 'Yes, the elevated M8 section through the city centre is one of our most frequent accident recovery locations, and our operators are experienced with the access and traffic management it requires.',
      },
      {
        question: 'Can you help with my insurance claim after recovery?',
        answer: 'Yes, we offer a free claims consultation covering documentation, insurer liaison and no-fault support once your vehicle is safely recovered.',
      },
    ],
    category: 'Glasgow',
    icon: '🚨',
  },
  {
    slug: 'accident-recovery-edinburgh',
    title: 'Accident Recovery in Edinburgh',
    headline: '24/7 Accident Recovery in Edinburgh',
    description: 'Accident recovery across Edinburgh and the Lothians, day or night. Scene management, safe vehicle loading and coordination with police and emergency services, followed by full claims support. Covering all EH postcodes. Under an hour response.',
    longDescription: `Edinburgh's Old Town cobbles, the busy A720 city bypass and the tram routes through the centre all bring their own challenges when a vehicle needs recovering after an accident. Glasgow Breakdown Recovery covers every EH postcode across the city and the Lothians, with an average response of 60–75 minutes.\n\nWe manage the scene for safety first, whether that's on a narrow Old Town street or the exposed hard shoulder of the bypass, then load and recover the vehicle with the right equipment for the damage. Coordination with police and emergency services is routine for us, and our free claims consultation picks up the insurance process once the vehicle is safely away.`,
    features: [
      'Covers all Edinburgh EH postcode districts',
      'A720 city bypass specialists',
      'Old Town and cobbled street recovery experience',
      'Tram route awareness in the city centre',
      'Coordination with police and emergency services',
      'Free accident claims consultation included',
      'Average response 60–75 minutes',
      'Available 24 hours a day, 365 days a year',
    ],
    faqs: [
      {
        question: 'Do you cover the A720 Edinburgh City Bypass?',
        answer: 'Yes, the bypass is one of our key operational routes in Edinburgh, and we have dedicated experience recovering vehicles from its hard shoulder and live lanes.',
      },
      {
        question: 'Can you reach Edinburgh quickly from Glasgow?',
        answer: 'We typically reach Edinburgh within 60–75 minutes. We also work with partner operators based in Edinburgh who can dispatch simultaneously for faster response where needed.',
      },
      {
        question: 'Is claims support included after an accident in Edinburgh?',
        answer: 'Yes, every accident recovery includes access to our free claims consultation, covering documentation and insurer liaison.',
      },
    ],
    category: 'Edinburgh',
    icon: '🚨',
  },
  {
    slug: 'breakdown-recovery-glasgow',
    title: 'Breakdown Recovery in Glasgow',
    headline: 'Broken Down in Glasgow?',
    description: "Broken down in Glasgow? We reach you fast, north or south of the river, 24 hours a day. Jump starts, tyre changes and roadside fixes attempted before any tow. Local recovery from £60 plus £1.50 per mile, quoted before we dispatch.",
    longDescription: `Whether you've broken down on a Southside residential street, in the West End, or heading out towards the East End, Glasgow Breakdown Recovery is based locally and dispatches directly, no call centre in between. We attempt a roadside fix first wherever possible, a jump start, a tyre change, a quick mechanical check, before assuming a tow is needed.\n\nWhen a fix isn't possible, we recover your car to your home, garage or destination of choice. Local recovery starts from £60 plus £1.50 per mile, and we confirm the exact price on the phone before anyone sets off.`,
    features: [
      'North and south of the river covered equally',
      'Roadside fixes attempted before towing',
      'Jump starts and tyre changes included',
      'Local recovery from £60 plus £1.50 per mile',
      'Price confirmed before dispatch',
      'No call centre, direct to the team',
      'Delivery to your home, garage or destination of choice',
      'Available 24 hours a day',
    ],
    faqs: [
      {
        question: 'How much does breakdown recovery cost in Glasgow?',
        answer: 'Local recovery starts from £60 plus £1.50 per mile, confirmed on the phone before we dispatch, so there are no surprises on arrival.',
      },
      {
        question: 'Can you fix my car at the roadside instead of towing it?',
        answer: 'In many cases yes: battery issues, flat tyres and minor mechanical problems can often be sorted on the spot. If not, we recover the vehicle to a garage.',
      },
    ],
    category: 'Glasgow',
    icon: '🔧',
  },
  {
    slug: 'breakdown-recovery-edinburgh',
    title: 'Breakdown Recovery in Edinburgh',
    headline: 'Breakdown Recovery Across Edinburgh',
    description: 'Breakdown recovery across Edinburgh and West Lothian, 24/7. Roadside repairs where possible, full recovery where not, to your home, garage or destination of choice. No membership needed. Clear price on the phone before we set off.',
    longDescription: `Edinburgh and the surrounding West Lothian area see everything from city centre breakdowns to motorway issues on the A720 and M8 approaches. Glasgow Breakdown Recovery covers the whole area, no membership required, attempting a roadside repair before recommending a tow wherever it's safe and practical to do so.\n\nIf your car does need recovering, we take it to your home, your usual garage, or wherever else suits you. You'll get a clear price on the phone before we set off, so there's no ambiguity when the truck arrives.`,
    features: [
      'Edinburgh and West Lothian coverage',
      'No membership or subscription needed',
      'Roadside repairs attempted first',
      'Full recovery to your chosen destination',
      'Clear price agreed before dispatch',
      'A720 and M8 approach experience',
      'All vehicle types covered',
      'Available 24/7, every day of the year',
    ],
    faqs: [
      {
        question: 'Do I need to be a member to use your breakdown service?',
        answer: 'No, there is no membership required. You call, we quote a price, and we come out, whether as a one-off or as often as you need.',
      },
      {
        question: 'Do you cover West Lothian as well as Edinburgh itself?',
        answer: 'Yes, our Edinburgh coverage extends across West Lothian, including Livingston and the surrounding towns.',
      },
    ],
    category: 'Edinburgh',
    icon: '🔧',
  },
  {
    slug: 'motorway-recovery-glasgow',
    title: 'Motorway Recovery in Glasgow',
    headline: 'Certified Motorway Recovery in Glasgow',
    description: 'Certified motorway recovery around Glasgow on the M8, M74, M77, M73 and M80. Live lane and hard shoulder attendance with correct signage, lighting and priority dispatch. £120 flat rate plus £1.50 per mile. Available 24 hours a day.',
    longDescription: `Glasgow sits at the meeting point of five motorways, the M8, M74, M77, M73 and M80, making it one of the busiest and most demanding areas in Scotland for motorway recovery. Our certified operators are trained for live-lane and hard shoulder working, with the correct signage, lighting and safety protocols required around Glasgow's junctions and interchanges.\n\nMotorway call-outs are given priority dispatch, because a vehicle stuck in a live lane cannot safely wait. Pricing is a flat rate of £120 plus £1.50 per mile, with no additional motorway surcharge on top.`,
    features: [
      'Covers the M8, M74, M77, M73 and M80 around Glasgow',
      'Certified live-lane and hard shoulder operators',
      'Correct signage and lighting on every job',
      'Priority dispatch for motorway call-outs',
      '£120 flat rate plus £1.50 per mile',
      'No additional motorway surcharge',
      'Coordination with Traffic Scotland and Police Scotland',
      'Available 24 hours a day',
    ],
    faqs: [
      {
        question: 'Which Glasgow motorways do you cover?',
        answer: 'We cover the M8, M74, M77, M73 and M80, including the interchanges where they meet around Glasgow.',
      },
      {
        question: 'How much does motorway recovery cost in Glasgow?',
        answer: 'A flat rate of £120 plus £1.50 per mile, with no extra motorway surcharge on top.',
      },
      {
        question: 'What should I do if I break down on the M8 through Glasgow?',
        answer: 'Reach the hard shoulder or nearest emergency refuge area if possible, put your hazards on, and exit from the passenger side away from traffic if it is safe to do so. Call us and we will dispatch immediately.',
      },
    ],
    category: 'Glasgow',
    icon: '🛣️',
  },
  {
    slug: 'flatbed-towing-glasgow',
    title: 'Flatbed Towing in Glasgow',
    headline: 'Flatbed Towing Across Glasgow',
    description: 'Flatbed towing across Glasgow on hydraulic tilt-bed transporters. Essential for AWD, 4x4, electric, prestige and modified vehicles, and for accident-damaged cars that cannot be conventionally towed. Fully insured in transit, available 24/7.',
    longDescription: `A growing share of the vehicles on Glasgow's roads simply cannot go on a conventional tow, all-wheel-drive cars, electric vehicles, prestige and modified cars with low ground clearance, and anything with accident damage severe enough to affect the wheels or steering. Our flatbed fleet, based locally, handles all of these routinely across the city.\n\nEvery flatbed job uses a hydraulic tilt-bed for a low, controlled loading angle, with the vehicle strapped securely for the journey. We're fully insured in transit and available across all Glasgow postcodes, 24 hours a day.`,
    features: [
      'Hydraulic tilt-bed flatbeds across all Glasgow postcodes',
      'Essential for AWD, 4x4 and electric vehicles',
      'Suited to prestige and modified cars',
      'Handles severely accident-damaged vehicles',
      'Fully insured in transit',
      'Low, controlled loading angle',
      'Secure strapping throughout the journey',
      'Available 24/7',
    ],
    faqs: [
      {
        question: 'Why do some cars need a flatbed instead of a normal tow in Glasgow?',
        answer: 'All-wheel-drive vehicles, EVs, and low, modified or prestige cars can be damaged by conventional towing. Flatbed transport keeps all four wheels off the road and avoids that risk.',
      },
      {
        question: 'Can you flatbed an accident-damaged car?',
        answer: 'Yes, severely damaged vehicles, especially where steering or suspension is affected, are safest and often only possible to move by flatbed.',
      },
    ],
    category: 'Glasgow',
    icon: '🚛',
  },
  {
    slug: 'motorcycle-recovery-glasgow',
    title: 'Motorcycle Recovery in Glasgow',
    headline: 'Motorcycle Recovery Across Glasgow',
    description: 'Motorcycle recovery in Glasgow using purpose-built transport and wheel chock securing systems, so your bike arrives exactly as it left. Sports bikes, scooters and accident-damaged machines. Available 24 hours a day across the city.',
    longDescription: `Motorcycles need dedicated equipment to recover safely, standard tie-down straps and ramps built for cars simply aren't suited to two wheels. Our Glasgow motorcycle recovery uses purpose-built loading ramps and wheel chock securing systems, so your bike is held upright and stable throughout the journey rather than resting on a side stand.\n\nWe cover sports bikes, scooters, cruisers and accident-damaged machines across every part of the city, from breakdowns on quiet residential streets to recoveries from the M8 and other busy routes.`,
    features: [
      'Purpose-built motorcycle transport vehicles',
      'Wheel chock securing systems, no side-stand resting',
      'Sports bikes, scooters and cruisers',
      'Accident-damaged motorcycle recovery',
      'City-wide Glasgow coverage',
      'Careful loading and unloading',
      'Same-day response in most cases',
      'Available 24 hours a day',
    ],
    faqs: [
      {
        question: 'Will my bike be secured properly during recovery?',
        answer: 'Yes, we use purpose-built wheel chocks and securing systems designed specifically for motorcycles, keeping the bike upright and stable rather than resting on its stand.',
      },
      {
        question: 'Can you recover a motorcycle that has been in an accident?',
        answer: 'Yes, we have the right equipment to load damaged motorcycles without causing further damage, from scene collection through to garage delivery.',
      },
    ],
    category: 'Glasgow',
    icon: '🏍️',
  },
  {
    slug: 'commercial-vehicle-recovery-glasgow',
    title: 'Commercial Vehicle Recovery in Glasgow',
    headline: 'Commercial Recovery Across Glasgow',
    description: 'Commercial recovery across Glasgow for vans, minibuses, light trucks and tippers up to 7.5t. Fast attendance because downtime costs money. Fleet accounts with priority dispatch and account invoicing. Available 24 hours a day, 365 days a year.',
    longDescription: `Glasgow's mix of industrial estates, retail parks and city centre delivery routes means commercial vehicles break down here every day, and every hour off the road costs a business money. We prioritise commercial call-outs across the city, recovering vans, minibuses, light trucks and tippers up to 7.5 tonnes.\n\nBusinesses with regular recovery needs can set up a fleet account for priority dispatch and monthly invoicing, removing the need to arrange payment on the day for every call-out.`,
    features: [
      'Vans, minibuses, light trucks and tippers up to 7.5t',
      'Priority dispatch for commercial call-outs',
      'Fleet accounts with monthly invoicing',
      'City-wide Glasgow coverage including industrial estates',
      'Suited to delivery and trade vehicles',
      'Fast attendance to minimise downtime',
      'One-off call-outs welcome, no account required',
      'Available 24 hours a day, 365 days a year',
    ],
    faqs: [
      {
        question: 'What size of commercial vehicle can you recover in Glasgow?',
        answer: 'We recover light commercial vehicles up to 7.5 tonnes, including transit-style vans, minibuses, light trucks and tippers.',
      },
      {
        question: 'Do I need a fleet account to use your commercial recovery service?',
        answer: 'No, one-off call-outs are welcome. A fleet account simply gives you priority dispatch and monthly invoicing if you need recovery regularly.',
      },
    ],
    category: 'Glasgow',
    icon: '🚚',
  },
  {
    slug: 'accident-claims-glasgow',
    title: 'Accident Claims Assistance in Glasgow',
    headline: 'Free Accident Claims Support in Glasgow',
    description: 'Free accident claims support across Glasgow. We document and photograph the scene at recovery, liaise with your insurer and guide no-fault claims through to settlement. No obligation on the initial consultation. Available 24 hours a day.',
    longDescription: `Dealing with an insurance claim on top of a road traffic accident in Glasgow is stressful, especially when you're not sure what you're entitled to. Our accident claims assistance starts the moment we recover your vehicle, documenting and photographing the scene and damage, then continuing on to liaise directly with your insurer.\n\nThe initial consultation is free and comes with no obligation, so you can find out exactly what support is available, including no-fault claim guidance and no-claims bonus protection, before deciding whether to go ahead.`,
    features: [
      'Free, no-obligation initial consultation',
      'Scene documentation and photography at recovery',
      'Direct liaison with your insurance provider',
      'No-fault accident claim guidance',
      'No-claims bonus protection support',
      'Courtesy car arrangement assistance',
      'City-wide Glasgow coverage',
      'Available 24 hours a day',
    ],
    faqs: [
      {
        question: 'Is the claims consultation really free?',
        answer: 'Yes, the initial consultation is free with no obligation to proceed. You decide afterwards whether you want our help with the claim.',
      },
      {
        question: 'How long do I have to make a claim in Scotland?',
        answer: 'For vehicle damage, notify your insurer promptly, ideally within 24 hours. For personal injury claims in Scotland, you generally have 3 years from the date of the accident.',
      },
    ],
    category: 'Glasgow',
    icon: '📋',
  },
]

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find(s => s.slug === slug)
}
